<html>
<title>MUKA LU KONTOL</title>
<link rel="shortcut icon" type="image/x-icon" href="https://f.top4top.io/s_3350zx51u0.jpeg">
<style>
html {
  background: url('https://i.postimg.cc/dQrhWhZC/huskyyq.jpg') no-repeat center center fixed;
  background-size: cover;
  color: green;
}
input {
  background: transparent;
  color: white;
  border: 1px solid white;
}
</style>
<center>
<h1>MUKA LU KAYA KONTOL </h1>
<img height="200" src="https://media.tenor.com/WYQnYdWsmrkAAAAM/hahaha-lol.gif"/><br><br>
<h3>SEO KEMARIN SORE</h3>

HALO BANG <input type="text" value="https://www.pornhub.com/video/search?search=brazzers" readonly>
<br><br>
<form enctype="multipart/form-data" method="post">
<input type="text" name="pass" placeholder="Password"> <input type="submit" value="SUBMIT">
</form>
<br>Copyright © 2025 Zayn | GANTENG
